language: rust
sudo: false

cache: cargo
rust:
  - stable
  - beta
  - nightly

env:
  global:
    - secure: EHYgVU/AQEnozaC/DiUoVZSrkjZoifBLDYS+bRIxPW7N/fSzNpwsgFSRj+Dt3Ushh8k5WqRRcmGPxnr8hX9N/JaAvBTwD1I4cQ/A/frX/vPkXMpxIUwCMpRC3cvqfgLWsEGReVWC6B5KDIHkHGFq7aNMFmGy2WtdETMgKcLHTzg=

addons:
  apt:
    packages:
      - gfortran

notifications:
  email: false
