[package]
name = "matrix"
version = "0.0.13"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/stainless-steel/matrix"
homepage = "https://github.com/stainless-steel/matrix"
documentation = "https://stainless-steel.github.io/matrix"
description = "The package provides algorithms for manipulating real matrices."

[dependencies]
blas = "0.0.13"
lapack = "0.0.13"

[dev-dependencies]
assert = "0.1"
