[package]
name = "matrix"
version = "0.0.1"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]

[dependencies.blas]
git = "https://github.com/stainless-steel/blas"

[dependencies.lapack]
git = "https://github.com/stainless-steel/lapack"

[dev-dependencies.assert]
git = "https://github.com/stainless-steel/assert"
