[package]
name = "matrix"
version = "0.20.0"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/stainless-steel/matrix"
homepage = "https://github.com/stainless-steel/matrix"
documentation = "https://stainless-steel.github.io/matrix"
description = "The package provides a matrix laboratory."

[features]
default = ["acceleration"]
acceleration = ["blas", "lapack"]

[dependencies.blas]
version = "0.14"
optional = true

[dependencies.lapack]
version = "0.9"
optional = true

[dependencies.num]
version = "0.1"
default-features = false
features = ["complex"]

[dev-dependencies]
assert = "0.6"
random = "0.9"
