[package]
name = "matrix"
version = "0.21.5"
license = "Apache-2.0/MIT"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
description = "The package provides a matrix laboratory."
documentation = "https://stainless-steel.github.io/matrix"
homepage = "https://github.com/stainless-steel/matrix"
repository = "https://github.com/stainless-steel/matrix"

[features]
default = ["acceleration"]
acceleration = ["blas", "lapack"]

[dependencies.blas]
version = "0.15"
optional = true

[dependencies.lapack]
version = "0.11"
optional = true

[dependencies.num-complex]
version = "0.1"
default-features = false

[dependencies.num-traits]
version = "0.1"

[dev-dependencies]
assert = "0.7"
random = "0.12"
