[package]
name = "matrix"
version = "0.0.1"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]

[lib]
name = "matrix"
doctest = false

[dependencies.blas]
git = "https://github.com/rs-math/blas"

[dependencies.lapack]
git = "https://github.com/rs-math/lapack"

[dev-dependencies.assert]
git = "https://github.com/stainless-steel/assert"
