[package]
name = "matrix"
version = "0.18.3"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/stainless-steel/matrix"
homepage = "https://github.com/stainless-steel/matrix"
documentation = "https://stainless-steel.github.io/matrix"
description = "The package provides a matrix laboratory."

[features]
acceleration = ["blas", "lapack"]
default = ["acceleration", "complex"]

[dependencies.blas]
version = "0.7"
optional = true

[dependencies.complex]
version = "0.7"
optional = true

[dependencies.lapack]
version = "0.6"
optional = true

[dev-dependencies]
assert = "*"
random = "*"
