[package]
name = "matrix"
version = "0.0.1"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/stainless-steel/matrix"
homepage = "https://github.com/stainless-steel/matrix"
documentation = "https://stainless-steel.github.io/matrix"
description = "The library provides algorithms for manipulating real matrices."

[dependencies.blas]
git = "https://github.com/stainless-steel/blas"

[dependencies.lapack]
git = "https://github.com/stainless-steel/lapack"

[dev-dependencies.assert]
git = "https://github.com/stainless-steel/assert"
